<a href="https://colab.research.google.com/github/Aniket3000/Assignments/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [0]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [0]:
print(np.__version__)

1.16.5


#### 3. Create a null vector of size 10 (★☆☆)

In [0]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [0]:
arr=np.zeros((4,4))
print(arr.size*arr.itemsize)

128


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [0]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [0]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [0]:
print(np.linspace(10,50,20))

[10.         12.10526316 14.21052632 16.31578947 18.42105263 20.52631579
 22.63157895 24.73684211 26.84210526 28.94736842 31.05263158 33.15789474
 35.26315789 37.36842105 39.47368421 41.57894737 43.68421053 45.78947368
 47.89473684 50.        ]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [0]:
arr=np.array([1,2,3,4])
#arr=np.flipud(arr)
arr=arr[::-1]
print(arr)

[4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [0]:
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [0]:
a=np.array([1,2,0,0,4,0])
for i in range(5):
  if(a[i]!=0):
    print(i)

0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [0]:
#arr.eye((3,3))
a=np.identity(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [0]:
print(np.random.randn(3,3,3))

[[[ 0.47011708 -0.44770231  1.78032624]
  [ 1.19340865 -1.96533594  0.11545082]
  [ 1.74903434  0.36685319  1.00899966]]

 [[ 0.53394481 -0.81832105  0.17921926]
  [-0.15614368  2.36690164 -0.30983539]
  [-1.60848114 -0.83365279 -1.36850773]]

 [[-0.76029309 -1.70586187 -0.54346298]
  [-0.42019272 -2.21377232  2.43606923]
  [ 0.61383749 -1.14317095 -0.08926621]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [0]:
a=np.random.randn(10,10)
print(a)
print(np.max(a))
print(np.min(a))

[[-1.51743781 -1.17089635 -0.12271733 -0.45828508 -1.47652126 -1.18351452
  -1.06758233 -1.26260216 -0.41688444  0.15590138]
 [-1.17594897  1.87183847  0.18523448  0.94580297  0.29782435  1.23734131
   0.35546163 -1.65593057 -1.75295283  0.91965117]
 [ 0.60222978  0.88181681 -0.71504519  1.02165403 -0.11801077  0.47411903
   1.15351767  1.11056193 -0.41242312 -1.49303643]
 [ 0.63704686 -0.14551587  1.18504111  0.19018342 -0.49958411 -0.58622698
   0.41857194 -0.24350289  0.4217573   0.9151597 ]
 [-1.55300061 -0.46882416  0.73960164 -1.39957084  0.16367092  1.00584071
  -1.07078794 -0.2553155  -0.66654708  0.01512493]
 [-1.72681148 -0.13108551  1.24718231  0.28740767 -0.48080379  1.3500774
   0.96606685 -0.48645866  1.85322036 -0.34931319]
 [-0.93829533 -1.6440435  -1.19249779  0.49259795  0.37674359  0.94917377
  -3.07521327  0.06748227  0.15507918  0.48681191]
 [ 1.24014705  0.89028283  0.13841804 -0.39578957  0.74593441  0.14184316
  -0.53411476 -0.38958277 -0.22482814 -0.74330077]
 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [0]:
a=np.random.random(30)
print(np.mean(a))
print(a)

0.4679835543805122
[0.82550665 0.67346101 0.57576543 0.70867878 0.33923143 0.78632585
 0.76954681 0.48689469 0.78025625 0.18398863 0.9006969  0.24395818
 0.1669389  0.1648275  0.80980562 0.4522284  0.21554663 0.2461471
 0.53881548 0.71520905 0.52801376 0.45036122 0.17067525 0.31730868
 0.36584546 0.74859271 0.36420991 0.21451522 0.01733395 0.27882118]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [0]:
x = np.ones((3,3))
x[1:-1,1:-1] = 0
print(x)


[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [0]:
a=np.ones((3,3))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [0]:
a=np.zeros((5,5))
print(np.tril([1,2,3,4,5],-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 2 0 0 0]
 [1 2 3 0 0]
 [1 2 3 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [0]:
2,1,3

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [0]:
np.tile?

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [0]:
np.normal?

Object `np.normal` not found.


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [0]:
a=np.random.random((5,3))
b=np.random.random((3,2))
print(a)
print(b)
print(a.dot(b))

[[0.64499248 0.6247206  0.06889283]
 [0.88737742 0.298041   0.08799086]
 [0.97272426 0.92941448 0.24026281]
 [0.85573705 0.86288785 0.63438238]
 [0.95889651 0.31181554 0.69061822]]
[[0.40405483 0.15187579]
 [0.02021192 0.26713705]
 [0.2468654  0.6877814 ]]
[[0.29024639 0.31222797]
 [0.38629502 0.27490743]
 [0.47113176 0.5612626 ]
 [0.51981237 0.79679146]
 [0.56423891 0.70392502]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [0]:
import pandas as pd
imdb_1000_data_url = r'data/imdb_1000.csv'
movies = pd.read_csv(imdb_1000_data_url)

FileNotFoundError: ignored

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)